### ISSUE TITLE
EncryptedServerSideMultipartManagerIT#cantUploadSmallMultipartString test failure

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#292]
This test has been failing since java-manta-3.0.0. It was brought to my attention again by @cburroughs when investigating test failures in java-manta-3.1.5. I've put together a PR that fixes the test but am questioning the need for the nested exception. Perhaps a new exception type might be useful for this specific scenario? `MantaMultipartUploadOrderException` or something similar?

**Comment by cburroughs** [comment]
> This test has been failing since java-manta-3.0.0.

This is not quiet correct. Another problem with this test was fixed in 0aea69d138ada511a9f76e0a425defb8788301ce and it was passing until a3f35075b662ec1e5e6dadfba2f7092d8d514326 as shown by the step from builds 29 <https://jenkins.joyent.us/job/java-manta-it/29/> to 30 <https://jenkins.joyent.us/job/java-manta-it/30/>

**Comment by tjcelaya** [comment]
Resolved by #293
