### ISSUE TITLE
Provide artifacts with no shaded dependencies

### ISSUE THREAD

**Issue by dkocher** [joyent/java-manta#307]

**Comment by cburroughs** [comment]
Could you elaborate on your use case for the alternative artifact?  Note that the shaded classes are also relocated, so there should be no conflict between (for example) `org.apache.http.client.HttpClient` and `com.joyent.manta.org.apache.http.client.HttpClient`.

**Comment by dkocher** [comment]
We don't want to have these libraries duplicated but manage versions of transitive dependencies ourselves.

**Comment by dekobon** [comment]
I see no technical reason why this isn't possible. The only gotcha is the dependency `com.twmacinta:fast-md5` that is coming from the `ci-jenkins` repository and not the oss-sonatype repository. We may need some Maven magic to properly embed the dependency all the while providing all of the other dependencies without shading.

The rational for shading has been that we haven't wanted to spend time on support when users have convergent dependency problems. Working on Java projects over the years, I have burned countless hours from user bug reports because of dependency convergence and users who are inexperienced with Maven.

My original intent with shading Apache Http Client was simply to remove the entire problem because most users can function just fine with a shaded artifact and it reduced our matrix of pain.

**Comment by tjcelaya** [comment]
Just to outline what our options are:

1. Bump the major version and publish `java-manta-client` as the unshaded artifact. This might be an unexpected change for users going from 3.1.6 to 4.0.0 and suddenly having dependency conflicts or pulling in previously-shaded dependencies.
2. Move the actual code in `java-manta-client` into an "internal" module and continue publishing the shaded artifact as `java-manta-client`. I was able to find a [few projects](https://search.maven.org/#search%7Cga%7C1%7Cunshaded) which publish a separate "$ARTIFACT-unshaded" artifact but it seems highly irregular. This might also clobber change attribution I believe.
3. Create an alternate profile that the `java-manta-client` module can use to change its artifact name and disable shading. This seems cumbersome and prone to breakage, e.g. do maintainers need to perform the release process twice, once for the `release` profile and again for the custom profile?

Regarding `com.twmacinta:fast-md5` coming from the `ci-jenkins` repository. Does that mean we _always_ need shading in the main module just for that particular dependency, or would say, `maven-assembly-plugin` be a better fit?

**Comment by dekobon** [comment]
Another option not mentioned that is a variation of #2 where we use a different classifier. We keep the default as shaded and provide a [classifier](https://maven.apache.org/pom.html#Maven_Coordinates) to an unshaded version. This way we don't change artifact names.

Regarding the `com.twmacinta:fast-md5` dependency, it really is the most confounding issue we face when changing to an unshaded archive.

1. We could put the source code directly in our source tree. This should be fine because we are using the MPLv2.
2. We could try to do a uber jar with the maven-assembly-plugin, but there will be hell for people importing the jar because they might want to create an uber jar as well.
3. We can attempt to move the author towards getting their library in Maven Central.
4. We can make our own fork and publish it to Maven Central.
5. We can document that you need to use the ci-jenkins repository if you inherit the unshaded artifact.

As for the above solutions, I do like #1 the best. If you are bumping a major version, you should read the CHANGELOG.

**Comment by cburroughs** [comment]
As much as it has burned me, I'd like to suggest that we continue to have java-manta-client be a shaded jar by default.  We know that shading makes sense for the largest use case for this library, and <https://github.com/joyent/hadoop-manta> is probably the 2nd largest (where it also makes sense).

By additionally providing a "-noshade" jar we can satisfy the (reasonable!) request for such a jar, avoid a major release, and keep the default in line with what makes sense with the (current) major use cases.  If it turns out that everyone prefers the "-noshade" jar, we can still flip those in the future. 

(If classifiers are the way to go but a maven tarpit, I can take a stab at it.)

@dekobon  also pointed out in   #326 some issues with how serialization interacts with shading.

**Comment by dekobon** [comment]
:+1:

**Comment by tjcelaya** [comment]
This should've been closed upon the release of 3.2.0 (2017-11-29), my mistake.
