### ISSUE TITLE
Lazily read ConfigContext in MantaClient

### ISSUE THREAD

**Issue by dkocher** [joyent/java-manta#311]
We would want to provide connection details after instantiation of the client and allow to change configuration options such as the `mantaKeyId` afterwards.

**Comment by dekobon** [comment]
The `MantaClient` class was designed so that each instance's runtime configuration is immutable. If you wanted to change the configuration, you would typically close an instance and then create another one.

If we were to introduce mutability into its state, then it may be possible by swapping out the `HttpHelper` and the `ConfigContext` instances. However, that would be very difficult to reasonable in a multi-threaded environment (which is very typical of a lot of users of Manta).

Imagine that you have instantiated a MantaClient, you now have passed it off to 4 threads that are using it to make concurrent requests to Manta. Now, I would like to change the runtime configuration of that class. How do I signal to the threads that they need to stop their operations so that I can destroy and recreate the connection pool / other runtime settings?

I wonder if we can introduce an abstraction that gives you an elegant way to integrate with the design of your application without adding complexity? Does anyone have any ideas?

**Comment by tjcelaya** [comment]
I have a `ReconfigurableMantaClient` sitting in a branch somewhere which acts as a proxy to an actual `MantaClient` and would `close` and discard the previous client before building a new one. The actual implementation was ugly (`MantaClient`'s methods were copied into an interface and implemented by both) so I was hesitant to propose it as a solution.

Alternatively, "closing" the `MantaClient` could be made more flexible by acting as a toggle instead of a one-off operation. Having the constructor delegate to a public `configure(ConfigContext)` method which grabs a lock and calls `close` as its first action would keep the configuration/thread-management lifecycle in the `MantaClient` class and avoid the creation of multiple unnecessary `MantaClient` objects.

In the end I could not decide between these two approaches but those are my suggestions.

**Comment by dekobon** [comment]
Both of those solutions seem viable to me.
