### ISSUE TITLE
some (many?) integration tests do not make use of the directories they create

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#319]
For example:

```
ffb4face-d811-44f7-818a-7b0bd0b6b3c1/
ffb4face-d811-44f7-818a-7b0bd0b6b3c1can-store-content-type-multipart-dba89491-664e-11e7-9adb-837b62e810e3.data
ffb4face-d811-44f7-818a-7b0bd0b6b3c1can-store-metadata-multipart-df367642-664e-11e7-9adb-efde733c5556.data
ffb4face-d811-44f7-818a-7b0bd0b6b3c1can-upload-5mb-multipart-binary-multipart-e36b6d63-664e-11e7-9adb-4f266722322e.data
ffb4face-d811-44f7-818a-7b0bd0b6b3c1can-upload-small-multipart-string-multipart-eb9ac3a4-664e-11e7-9adb-69c5dce3f7ae.data
ffb4face-d811-44f7-818a-7b0bd0b6b3c1will-run-function-when-waiting-too-long-multipart-ef4fb555-664e-11e7-9adb-b3c6da73fd92.data
```

The objects should be *inside* the directory, not just happening to share a prefix.

**Comment by cburroughs** [comment]
Besides aesthetics, I think this means `AfterClass` cleanup is missing these objects:

```
            this.mantaClient.deleteRecursive(testPathPrefix);
```

**Comment by tjcelaya** [comment]
I started to address this as part of the documentation PR for some reason but the issue stems from copy-pasted code that was wrong the first time and proliferated:

```
        testPathPrefix = String.format("%s/stor/java-manta-integration-tests/%s",
                config.getMantaHomeDirectory(), UUID.randomUUID());
```

Since `testPathPrefix` is missing the trailing slash most of the object paths end up in the situation you described. I can pull the commits that fixed this out of the documentation PR and make that its own PR.

**Comment by cburroughs** [comment]
I tested this in staging since the diff landed and things look much better.
