### ISSUE TITLE
update USAGE for new security policy policy

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#420]
https://bugs.openjdk.java.net/browse/JDK-8157561

I have been unable to find a single document that explains all of the changes. 
 * As of 8u152, the unlimited strength policy jars are shipped with the JDK.  No more jumping through hoops to download manually.
 * At least on ubuntu/OpenJDK, `crypto.policy=unlimited` is the default.

**Comment by tjcelaya** [comment]
This was updated in c0e7982e200b98cce142677d0bd2bb5c56a57973 before this issue was opened, though I reference a different Java version since the 8u152 change is specifically just `crypto.policy` relevant to JDK while 8u161 was about turning it on by default and is more relevant to end users (i.e. folks not using JDK).

Updated the section to disambiguate the two.
