### ISSUE TITLE
Implement progress listener for data transfers

### ISSUE THREAD

**Issue by phillipross** [joyent/java-manta#63]
It would be extremely helpful for applications to be able to register listeners with the manta client api for the purpose of monitoring progress with larger data transfers.

**Comment by dekobon** [comment]
How would this be different than wrapping your stream in something like a [CountingInputStream](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CountingInputStream.html)

**Comment by dekobon** [comment]
I'm going to make this as closed because in the [2.4.0 release](https://github.com/joyent/java-manta/releases/tag/java-manta-2.4.0) we offer OutputStream as part of the API. With InputStream and OutputStream, consumers of the API should be able to build their own listeners that count the number of bytes read and update progress like how it is done in the [Manta Hadoop FileSystem](https://github.com/joyent/hadoop-manta/blob/master/src/main/java/com/joyent/hadoop/fs/manta/ProgressingOutputStream.java) implementation.
